# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65abc7a3994e3d18c0587c4d4c7b1b190152a1cc7071ef2a6d2169f23008d1ed21445b38ff0e595d4734a2c67cf61c06e40eac20fdafe21bc77292a083ffd8e0

test:
  secret_key_base: ac2709cdbc31189eeaee4de6775d9702d88091352897faaf9b4cf501d19e976c7f26c7b12c47438849b3e6d29b071bf103fd8a8dbd37108f44fccbfddb2f6b21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
